# SPDX-License-Identifier: GPL-3.0-or-later
"""Every settings panel builds, and none of them is a wall of rows.

Panels are built from a callback rather than retained, so a mistake in one
of them is not a syntax error — it is an exception the first time somebody
opens that section, on a television, with a remote. This walks all of them
in one headless pass.

The second half is the reason the groups exist: Appearance ran to fifteen
rows, Input and System to fourteen, of which about nine fit on the screen.
A panel above the fold limit has to say where its groups start.
"""

from __future__ import annotations

import os

# GSettings, in memory and nowhere else. A dconf *write* is a D-Bus call to
# the writer daemon, which resolves the user database from its own
# environment, so redirecting the XDG directories is not enough. Assigned
# rather than `setdefault`, and before `gi.repository` is imported, which is
# when the backend is chosen. Enforced by tests/test_settings_isolation.py.
os.environ["GSETTINGS_BACKEND"] = "memory"

import pytest  # noqa: E402

gi = pytest.importorskip("gi")
gi.require_version("Gtk", "4.0")

from gi.repository import Gio, Gtk  # noqa: E402

# `salon/config.py` is generated by Meson from `config.py.in`, so it exists
# in the build tree and not in the source tree — and the panels reach it
# through the artwork and autostart services. pytest runs with the source
# tree on the path (`pythonpath = ["."]`), so the ordinary pass skips this
# file and `scripts/check.sh` runs it a second time once a build exists:
#
#     pytest -q -o pythonpath=build tests/test_settings_panels_build.py
#
# Skipping rather than failing keeps `pytest tests/` usable on a fresh
# checkout, where there is no build tree to import from yet.
pytest.importorskip("salon.config", reason="run against a built tree to exercise the panels")

from salon.core.config import Config  # noqa: E402
from salon.ui.scale import Scale  # noqa: E402
from salon.ui.settings import panels  # noqa: E402
from salon.ui.settings.context import Panel, SettingsContext  # noqa: E402
from salon.ui.settings.row_panels import rows_panel  # noqa: E402
from salon.ui.settings.static_rows import GroupRow  # noqa: E402

# Roughly what fits on a 1080p screen at the shipped row height. A panel
# longer than this without headings is a haystack.
_VISIBLE_ROWS = 9


def _settings() -> Gio.Settings:
    source = Gio.SettingsSchemaSource.get_default()
    schema = source.lookup("io.github.alexydaher.Salon", True) if source else None
    if schema is None:
        pytest.skip("Salon's compiled schema is not on GSETTINGS_SCHEMA_DIR")
    return Gio.Settings.new_full(schema, None, None)


def _context() -> SettingsContext:
    return SettingsContext(
        config=Config(),
        save_config=lambda: None,
        toast=lambda _m: None,
        edit_text=lambda _p, _c, _d: None,
        choose_path=lambda _p, _f, _d: None,
        push=lambda _p: None,
        pop=lambda: None,
        rebuild=lambda: None,
        quit_app=lambda: None,
        close=lambda: None,
        installed_apps=lambda _cb: None,
        open_control_center=lambda _p: None,
        phone_remote_running=lambda: False,
        set_phone_remote=lambda _e: True,
        phone_remote_hint=lambda: "",
        pointer_backend=lambda: "",
        bindings=lambda: _Bindings(),
        capture_binding=lambda _cb: None,
        cancel_capture=lambda: None,
        rebind=lambda _s, _c, _a: None,
        reset_bindings=lambda: None,
        # Keyword-only, exactly like `ArtworkResolver.resolve`: a stub that
        # took it positionally is what let a TypeError reach the tile
        # editor with every gate green.
        resolve_artwork=_resolve_artwork,
        scale=lambda: Scale(1080),
        version="0.0.0",
        config_path="/tmp/salon-test/tiles.json",
    )


def _resolve_artwork(_tile: object, *, icon_size: int) -> object:
    from gi.repository import Gdk

    from salon.services.artwork_models import Artwork

    assert icon_size > 0
    return Artwork(accent=Gdk.RGBA())


class _Bindings:
    def keys_for(self, _action: str) -> list[str]:
        return []


def _sections() -> list[Panel]:
    Gtk.init()
    context = _context()
    settings = _settings()
    return [
        panels.setup_panel(context, settings),
        rows_panel(context),
        panels.appearance_panel(context, settings),
        panels.audio_panel(context, settings),
        panels.input_panel(context, settings),
        panels.network_panel(context, settings),
        panels.system_panel(context, settings),
        panels.about_panel(context, settings),
    ]


@pytest.mark.parametrize("index", range(8))
def test_every_section_builds(index: int) -> None:
    panel = _sections()[index]
    rows = panel.build()
    assert rows, panel.title
    assert all(hasattr(row, "hint") for row in rows)


def test_a_long_panel_says_where_its_groups_start() -> None:
    for panel in _sections():
        rows = panel.build()
        if len(rows) <= _VISIBLE_ROWS:
            continue
        assert any(isinstance(row, GroupRow) for row in rows), (
            f"{panel.title} is {len(rows)} rows with no headings; "
            f"about {_VISIBLE_ROWS} of them fit on the screen"
        )


def test_a_group_heading_never_ends_a_panel() -> None:
    """A heading with nothing under it is a heading for the fold."""
    for panel in _sections():
        rows = panel.build()
        assert not isinstance(rows[-1], GroupRow), panel.title


def test_every_section_describes_itself_in_the_list() -> None:
    """Eight identical lines of one word each gave the eye nothing to aim
    at from a sofa; every section says what it is or what it is set to."""
    for panel in _sections():
        assert panel.subtitle or panel.summary is not None, panel.title
        assert panel.icon_name, panel.title
        assert panel.panel_id, panel.title


def test_section_ids_are_unique() -> None:
    ids = [panel.panel_id for panel in _sections()]
    assert len(set(ids)) == len(ids)
