"""The APT archive and the instructions for adding it must describe one thing.

Nothing else connects them: the archive's suite and component live in a shell
script, the landing page is generated by a Python one, and the README is
prose. A person following instructions that name a suite the archive does not
publish gets "no Release file", with no hint which half is wrong.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parent.parent
BUILD_SCRIPT = ROOT / "scripts" / "build-apt-repository.sh"
KEYRING = "salon-archive-keyring.gpg"
KEYRING_PATH = f"/etc/apt/keyrings/{KEYRING}"


def load_installer_script() -> ModuleType:
    path = ROOT / "scripts" / "prepare-flatpak-repository.py"
    spec = importlib.util.spec_from_file_location("prepare_flatpak_repository", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def archive_settings() -> dict[str, str]:
    text = BUILD_SCRIPT.read_text()
    return dict(re.findall(r"^([A-Z_]+)='([^']*)'$", text, flags=re.MULTILINE))


def source_stanza() -> list[str]:
    settings = archive_settings()
    installer = load_installer_script()
    site = installer.DEFAULT_REPOSITORY_URL.removesuffix("repo/")
    return [
        f"URIs: {site}apt",
        f"Suites: {settings['SUITE']}",
        f"Components: {settings['COMPONENT']}",
        f"Signed-By: {KEYRING_PATH}",
    ]


def test_the_archive_publishes_the_suite_and_component_the_docs_name() -> None:
    settings = archive_settings()
    assert settings["SUITE"]
    assert settings["COMPONENT"]
    assert settings["ARCHITECTURE"] == "all", "debian/control builds one package"
    assert KEYRING in BUILD_SCRIPT.read_text()

    for line in source_stanza():
        assert line in (ROOT / "README.md").read_text(), line


def test_the_landing_page_hands_out_the_same_source() -> None:
    installer = load_installer_script()
    site = installer.DEFAULT_REPOSITORY_URL.removesuffix("repo/")
    setup = installer.apt_setup(site)

    for line in source_stanza():
        assert line in setup, line
    assert f"{site}apt/{KEYRING}" in setup
    assert KEYRING_PATH in setup
