#!/usr/bin/env python3
"""Generate data/style/tokens.css from salon.core.tokens.

Invoked by Meson at build time (see data/style/meson.build). The generated
file is the only place GTK CSS learns Salon's colour tokens — never
hand-edit tokens.css, edit salon/core/tokens.py instead.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from salon.core.tokens import COLORS  # noqa: E402


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen-tokens-css.py OUTPUT", file=sys.stderr)
        return 1

    output = Path(argv[1])
    lines = [
        "/* Generated by build-aux/gen-tokens-css.py from salon/core/tokens.py. */",
        "/* Do not hand-edit. */",
        "",
    ]
    lines.extend(f"@define-color {token.name} {token.value};" for token in COLORS)
    output.write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
